/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 0.1.0
 */

/**
 * /me のレスポンス。users.id と profiles の username / email を返す。
 */
export interface MeResponse {
  email: string;
  userId: string;
  username: string;
}
