/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 0.1.0
 */

export interface RefreshRequest {
  /** 再発行に使う refresh トークン（ボディで送信） */
  refreshToken: string;
}
