/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 0.1.0
 */

export interface SigninRequest {
  /** Firebase Auth で発行された ID トークン（ボディで送信） */
  idToken: string;
}
