/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 0.1.0
 */

export interface SignupRequest {
  email: string;
  firebaseUid: string;
  username: string;
}
