/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 0.1.0
 */

/**
 * Signup API のレスポンス用 DTO
 */
export interface SignupResponse {
  accessToken: string;
  refreshToken: string;
}
